# ==============================
# Base: CUDA 12.4 + Ubuntu 22.04
# ==============================
ARG UBUNTU_VERSION=22.04
ARG CUDA_VERSION=12.8.1

FROM nvidia/cuda:${CUDA_VERSION}-devel-ubuntu${UBUNTU_VERSION}

ENV DEBIAN_FRONTEND=noninteractive
SHELL ["/bin/bash", "-c"]

# ==============================
# System Dependencies
# ==============================
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential \
    g++ \
    gcc \
    make \
    git \
    wget \
    curl \
    vim \
    ninja-build \
    pkg-config \
    ca-certificates \
    gnupg2 \
    lsb-release \
    software-properties-common \
    python3-pip \
    python3-dev \
    python3-venv \
    libgl1 \
    libglew2.2 \
    libgoogle-glog0v5 \
    libqt5core5a \
    libqt5gui5 \
    libqt5widgets5 \
    libxcb-cursor0 \
    libxcb-xinerama0 \
    libxkbcommon-x11-0 \
    libxcb-xinput0 \
    libflatbuffers-dev \
    && rm -rf /var/lib/apt/lists/*

# ==============================
# Install RealSense SDK
# ==============================
#RUN mkdir -p /etc/apt/keyrings && \
#    curl -fsSL https://librealsense.intel.com/Debian/librealsense.pgp | gpg --dearmor -o /etc/apt/keyrings/librealsense.gpg && \
#    echo "deb [signed-by=/etc/apt/keyrings/librealsense.gpg] \
#    https://librealsense.intel.com/Debian/apt-repo \
#    $(lsb_release -cs) main" \
#    > /etc/apt/sources.list.d/librealsense.list && \
#    apt-get update && \
#    apt-get install -y librealsense2-dev librealsense2-utils && \
#    rm -rf /var/lib/apt/lists/*

# ==============================
# Install ROS 2 humble
# ==============================
RUN mkdir -p /etc/apt/keyrings && \
    curl -sSL https://raw.githubusercontent.com/ros/rosdistro/master/ros.key \
    -o /usr/share/keyrings/ros-archive-keyring.gpg && \
    echo "deb [arch=$(dpkg --print-architecture) signed-by=/usr/share/keyrings/ros-archive-keyring.gpg] \
    http://packages.ros.org/ros2/ubuntu \
    $(lsb_release -cs) main" \
    > /etc/apt/sources.list.d/ros2.list && \
    apt-get update && \
    apt-get install -y --no-install-recommends \
    ros-humble-desktop \
    python3-colcon-common-extensions \
    python3-vcstool \
    python3-empy \
    ros-humble-realsense2-camera \
    ros-humble-vision-msgs \
    && rm -rf /var/lib/apt/lists/*
    
# ==============================
# Pytorch
# ==============================  
RUN pip3 install --no-cache-dir \
    torch torchvision \
    --index-url https://download.pytorch.org/whl/cu128
    
# ==============================
# Python ML / Vision Dependencies
# ==============================
RUN pip3 install --no-cache-dir \
    ultralytics \
    numpy==1.26 \
    pyrealsense2 

# ==============================
# Environment Setup
# ==============================
ENV ROS_DISTRO=humble
ENV RMW_IMPLEMENTATION=rmw_cyclonedds_cpp

RUN echo "source /opt/ros/${ROS_DISTRO}/setup.bash" >> /root/.bashrc

WORKDIR /workspace

CMD ["/bin/bash"]
