camera_yolo_detector:
  ros__parameters:
    color_topic: "/camera/camera/color/image_rect_raw"
    depth_topic: "/camera/camera/depth/image_rect_raw"
    camera_info_topic: "/camera/camera/color/camera_info"
    flip_image: true
    detection_topic: "/detections"
    detection_3d_topic: "/detections_3d"
    debug_mode: true
    debug_image_topic: "/debug/detections_image"
    confidence_threshold: 0.25
    sync_tolerance_sec: 0.04
    depth_scale_meters: 0.001
    min_volume_m: 0.000008
    max_volume_m: 0.001
    yolo_weights_path: ""
    yolo_device: ""
    processing_period_sec: 0.001
    log_every_n_frames: 300
